# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 970996b2cedaa6db1c48f8ac0042eaddd1fc6e735b1d8a05d2368284ab440f0af9066b3bb8672de40685344af89797e4d0d812f4545078dfc849043ef8eebc5a

test:
  secret_key_base: 6f10ad83dfdad61cb1ac4e04e0d8fe4f32ed1b9e3f1395b2e85ba6d120293e4ee6092810ef569015451eb1b860a29f988c79e5c2f132afa15c85f9d88c720c1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
